#Configuracion del puerto
server.port=8080
spring.application.name=proyecto

#Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admineduardox624
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Configuracion de CORS para React
spring.mvc.cors.allowed-origins=http://localhost:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS